
  CREATE TABLE "ACCOUNT" 
   (	"ACCOUNT_ID" VARCHAR2(20) NOT NULL, 
	"EMAIL" VARCHAR2(200) NOT NULL, 
	"PASSWORD" VARCHAR2(30) NOT NULL, 
	"NAME" VARCHAR2(100) NOT NULL, 
	"ADDRESS" VARCHAR2(200) NOT NULL, 
	"ROUTING_NUMBER" VARCHAR2(9) NOT NULL, 
	"ACCOUNT_NUMBER" VARCHAR2(12) NOT NULL, 
	"UPDATED_DATE" DATE NOT NULL, 
	"CREATED_DATE" DATE NOT NULL, 
	 CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ACCOUNT_ID")
   );

  CREATE TABLE "CURRENCY" 
   (	"CURRENCY_ID" VARCHAR2(20) NOT NULL, 
	"CURRENCY_NAME" VARCHAR2(20) NOT NULL, 
	"UPDATED_DATE" DATE NOT NULL, 
	"CREATED_DATE" DATE NOT NULL, 
	 CONSTRAINT "CURRENCY_PK" PRIMARY KEY ("CURRENCY_ID")
   );

  CREATE TABLE "BALANCE" 
   (	"ACCOUNT_ID" VARCHAR2(20) NOT NULL, 
	"CURRENCY_ID" VARCHAR2(20) NOT NULL, 
	"BALANCE" NUMBER NOT NULL, 
	"UPDATED_DATE" DATE NOT NULL, 
	"CREATED_DATE" DATE NOT NULL, 
	 CONSTRAINT "BALANCE_FK1" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "ACCOUNT" ("ACCOUNT_ID"), 
	 CONSTRAINT "BALANCE_FK2" FOREIGN KEY ("CURRENCY_ID")
	  REFERENCES "CURRENCY" ("CURRENCY_ID")
   ) ;

  CREATE TABLE "ORDER_" 
   (	"ORDER_ID" VARCHAR2(20) NOT NULL, 
	"ACCOUNT_ID" VARCHAR2(20) NOT NULL, 
	"BUY_SELL_TYPE" VARCHAR2(4) NOT NULL, 
	"ORDER_CURRENCY_ID" VARCHAR2(20) NOT NULL, 
	"ORDER_LIMIT_PRICE" NUMBER NOT NULL, 
	"ORDER_AMOUNT" NUMBER NOT NULL, 
	"ORIGINAL_CURRENCY_ID" VARCHAR2(20) NOT NULL, 
	"ORIGINAL_AMOUNT" NUMBER NOT NULL, 
	"STATUS" VARCHAR2(10) NOT NULL, 
	"UPDATED_DATE" DATE NOT NULL, 
	"CREATED_DATE" DATE NOT NULL, 
	 CONSTRAINT "ORDER_PK" PRIMARY KEY ("ORDER_ID"), 
	 CONSTRAINT "ORDER__FK1" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "ACCOUNT" ("ACCOUNT_ID"), 
	 CONSTRAINT "ORDER__FK2" FOREIGN KEY ("ORDER_CURRENCY_ID")
	  REFERENCES "CURRENCY" ("CURRENCY_ID"), 
	 CONSTRAINT "ORDER__FK3" FOREIGN KEY ("ORIGINAL_CURRENCY_ID")
	  REFERENCES "CURRENCY" ("CURRENCY_ID")
   );

  CREATE TABLE "TRANSACTION" 
   (	"TRANSACTION_ID" VARCHAR2(20) NOT NULL, 
	"TRANSACTION_TYPE" VARCHAR2(10) NOT NULL, 
	"ACCOUNT_ID" VARCHAR2(20) NOT NULL, 
	"DEBIT_CURRENCY_ID" VARCHAR2(20) NOT NULL, 
	"DEBIT_AMOUNT" NUMBER NOT NULL, 
	"CREDIT_CURRENCY_ID" VARCHAR2(20) NOT NULL, 
	"CREDIT_AMOUNT" NUMBER NOT NULL, 
	"UPDATED_DATE" DATE NOT NULL, 
	"CREATED_DATE" DATE NOT NULL, 
	"PAYER_ROUTING_NUMBER" VARCHAR2(9), 
	"PAYER_ACCOUNT_NUMBER" VARCHAR2(12), 
	"CRYPTOCCY_TRANSACTION_ID" VARCHAR2(34), 
	"MY_ORDER_ID" VARCHAR2(20), 
	"COUNTER_ORDER_ID" VARCHAR2(20), 
	"RCPT_ROUTING_NUMBER" VARCHAR2(9), 
	"RCPT_ACCOUNT_NUMBER" VARCHAR2(12), 
	"CRYPTOCCY_TRANSACTION_ID2" VARCHAR2(64), 
	 CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("TRANSACTION_ID"), 
	 CONSTRAINT "TRANSACTION_FK1" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "ACCOUNT" ("ACCOUNT_ID"), 
	 CONSTRAINT "TRANSACTION_FK2" FOREIGN KEY ("DEBIT_CURRENCY_ID")
	  REFERENCES "CURRENCY" ("CURRENCY_ID"), 
	 CONSTRAINT "TRANSACTION_FK3" FOREIGN KEY ("CREDIT_CURRENCY_ID")
	  REFERENCES "CURRENCY" ("CURRENCY_ID"), 
	 CONSTRAINT "TRANSACTION_FK4" FOREIGN KEY ("MY_ORDER_ID")
	  REFERENCES "ORDER_" ("ORDER_ID"), 
	 CONSTRAINT "TRANSACTION_FK5" FOREIGN KEY ("COUNTER_ORDER_ID")
	  REFERENCES "ORDER_" ("ORDER_ID")
   );
